package sk.ainet.apps.kllama

import java.lang.foreign.Arena
import java.nio.file.Path
import kotlin.io.path.exists
import kotlin.io.path.readText
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import org.junit.jupiter.api.Tag
import sk.ainet.apps.llm.OptimizedLLMMode
import sk.ainet.apps.llm.OptimizedLLMRuntime
import sk.ainet.context.DirectCpuExecutionContext
import sk.ainet.io.JvmRandomAccessSource
import sk.ainet.lang.tensor.data.MemorySegmentTensorDataFactory
import sk.ainet.lang.types.FP32
import sk.ainet.models.qwen.QwenNetworkLoader
import sk.ainet.models.qwen.fromGgufNative

/**
 * Phase-4 readiness gate (#118): does the DSL Qwen path agree with
 * llama.cpp on greedy top-1 tokens for a real Qwen3 GGUF?
 *
 * The reference fixture is generated by
 * `tests/ground-truth/qwen3/generate_reference.py` (see
 * [tests/ground-truth/qwen3/README.md] for the regeneration command).
 * Both this test and the Python generator load the **same GGUF bytes**;
 * the comparison is between two inference engines on identical inputs
 * — apples-to-apples, no weight-conversion variable.
 *
 * Skip behaviour: skips gracefully if either the model GGUF or the
 * reference JSON is missing, so checking this test in alongside the
 * harness is safe before any maintainer has regenerated the fixture.
 *
 * Pass criterion: top-1 token must match llama.cpp at every step of
 * every prompt. Strict equality — top-1 is a discrete decision, no
 * numerical tolerance applies.
 */
@Tag("integration")
class QwenHfReferenceParityTest {

    companion object {
        /** Path to the generated reference. Override via env var if needed. */
        private val FIXTURE_PATH: Path = run {
            val env = System.getenv("QWEN3_REFERENCE_FIXTURE")
            if (env != null) Path.of(env)
            else Path.of(
                System.getProperty("user.dir"),
                "../../tests/ground-truth/qwen3/results/qwen3-1.7B-q8_0.json",
            ).normalize()
        }
    }

    @Serializable
    private data class Reference(
        val model_path: String,
        val model_filename: String,
        val n_steps: Int,
        val topk: Int,
        val llama_cpp_python_version: String,
        val prompts: List<PromptRef>,
    )

    @Serializable
    private data class PromptRef(
        val id: String,
        val text: String,
        val prompt_token_ids: List<Int>,
        val steps: List<StepRef>,
    )

    @Serializable
    private data class StepRef(
        val step: Int,
        val top1_id: Int,
        val top1_logit: Double,
        val topk_ids: List<Int>,
        val topk_logits: List<Double>,
    )

    @Test
    fun `DSL Qwen agrees with llama_cpp on greedy top-1 across reference prompts`() {
        if (!FIXTURE_PATH.exists()) {
            println(
                "SKIP: reference fixture not found at $FIXTURE_PATH. " +
                    "Generate it via tests/ground-truth/qwen3/generate_reference.py.",
            )
            return
        }
        val ref: Reference = Json { ignoreUnknownKeys = true }
            .decodeFromString(Reference.serializer(), FIXTURE_PATH.readText())

        val modelPath = Path.of(ref.model_path)
        if (!modelPath.exists()) {
            println(
                "SKIP: reference says GGUF is at $modelPath but it doesn't exist. " +
                    "Either move the model there, or regenerate the fixture against " +
                    "a model that does exist.",
            )
            return
        }
        println(
            "Qwen DSL ↔ llama.cpp parity gate (#118) — model=${ref.model_filename}, " +
                "${ref.prompts.size} prompts × ${ref.n_steps} steps, " +
                "llama-cpp-python v${ref.llama_cpp_python_version}",
        )

        val memSegFactory = MemorySegmentTensorDataFactory()
        val ctx = DirectCpuExecutionContext(tensorDataFactory = memSegFactory)
        Runtime.getRuntime().addShutdownHook(Thread { memSegFactory.close() })

        Arena.ofConfined().use { arena ->
            val model = kotlinx.coroutines.runBlocking {
                QwenNetworkLoader.fromGgufNative(
                    randomAccessProvider = { JvmRandomAccessSource.open(modelPath.toString()) },
                    ctx = ctx,
                    arena = arena,
                )
            }
            val runtime = OptimizedLLMRuntime(model, ctx, OptimizedLLMMode.DIRECT, FP32::class)

            for (prompt in ref.prompts) {
                runtime.reset()
                // Prefill
                for (tokenId in prompt.prompt_token_ids) {
                    runtime.forward(tokenId)
                }
                // Greedy decode against reference
                var lastToken = prompt.prompt_token_ids.last()
                for ((step, expected) in prompt.steps.withIndex()) {
                    val logits = runtime.forward(lastToken).data.copyToFloatArray()
                    val dslTop1 = argmax(logits)
                    if (dslTop1 != expected.top1_id) {
                        // Surface diagnostic context — top-K from both engines.
                        val dslTopK = topK(logits, ref.topk)
                        val expectedFmt = expected.topk_ids.zip(expected.topk_logits)
                            .joinToString(", ") { (id, logit) -> "$id (${"%.4f".format(logit)})" }
                        val dslFmt = dslTopK.joinToString(", ") { (id, logit) -> "$id (${"%.4f".format(logit)})" }
                        assertEquals(
                            expected.top1_id, dslTop1,
                            "prompt='${prompt.id}' step=$step  DSL top-1=$dslTop1 " +
                                "vs llama.cpp top-1=${expected.top1_id}\n" +
                                "  llama.cpp top-${ref.topk}: $expectedFmt\n" +
                                "  DSL       top-${ref.topk}: $dslFmt",
                        )
                    }
                    lastToken = dslTop1
                }
                println("  ${prompt.id}: ✓ ${prompt.steps.size} steps agree")
            }
        }
    }

    private fun argmax(logits: FloatArray): Int {
        var best = 0
        var bestVal = logits[0]
        for (i in 1 until logits.size) {
            if (logits[i] > bestVal) {
                bestVal = logits[i]
                best = i
            }
        }
        return best
    }

    private fun topK(logits: FloatArray, k: Int): List<Pair<Int, Float>> {
        // Simple O(n*k) — k is small (5-ish).
        val taken = BooleanArray(logits.size)
        val out = ArrayList<Pair<Int, Float>>(k)
        repeat(k) {
            var best = -1
            var bestVal = Float.NEGATIVE_INFINITY
            for (i in logits.indices) {
                if (!taken[i] && logits[i] > bestVal) {
                    bestVal = logits[i]
                    best = i
                }
            }
            if (best < 0) return@repeat
            taken[best] = true
            out += best to bestVal
        }
        return out
    }
}
