site:
  title: SKaiNET Transformers
  start_page: skainet-transformers::index.adoc

content:
  sources:
    - url: .
      start_path: docs
      branches: HEAD

asciidoc:
  extensions:
    - asciidoctor-kroki

kroki:
  server-url: https://kroki.io
  fetch-diagram: true

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  dir: ./build/site
